services:
  - type: web
    name: high_dim_survey
    runtime: python
    buildCommand: cd frontend && npm install && npm run build && cd .. && pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free

    envVars:
      - key: RESEND_API_KEY
        sync: false
      - key: NOTIFY_EMAIL
        value: vlad12vranceanu@gmail.com
